# Generated by Django 6.0.4 on 2026-04-28 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorylog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='inventorylog',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='inventorylog',
            old_name='change',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='action',
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='type',
            field=models.CharField(choices=[('ADD', 'Add'), ('REMOVE', 'Remove')], default='ADD', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
